#ifndef TRITON_DIALECT_TRITONGPU_TRANSFORMS_ADVANCEDPIPELINER_H
#define TRITON_DIALECT_TRITONGPU_TRANSFORMS_ADVANCEDPIPELINER_H

#include "triton/Dialect/TritonGPU/Transforms/BufferAccessAnalysis.h"
#include "triton/Dialect/TritonGPU/Transforms/PipelineOpportunityDetector.h"
#include "triton/Dialect/TritonGPU/Transforms/CircularBufferTransform.h"
#include "triton/Dialect/TritonGPU/Transforms/SynchronizationInsertion.h"
#include "mlir/Pass/Pass.h"

namespace mlir {
namespace triton {
namespace gpu {

// Forward declaration - actual pass class is generated by TableGen
// See: triton/Dialect/TritonGPU/Transforms/Passes.td
// The TableGen-generated pass is: impl::TritonGPUAdvancedPipelinerBase

/// Create the advanced pipeliner pass
/// Note: This function is auto-generated by TableGen
// std::unique_ptr<Pass> createAdvancedPipelinerPass();
// Use createTritonGPUAdvancedPipeliner() instead (from TableGen)

} // namespace gpu
} // namespace triton
} // namespace mlir

#endif // TRITON_DIALECT_TRITONGPU_TRANSFORMS_ADVANCEDPIPELINER_H
